In [1]:
import pandas as pd 

df = pd.read_csv("Customer-Churn-Records.csv")

In [2]:
df.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Complain,Satisfaction Score,Card Type,Point Earned
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1,1,2,DIAMOND,464
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0,1,3,DIAMOND,456
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1,1,3,DIAMOND,377
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0,0,5,GOLD,350
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0,0,5,GOLD,425

In [3]:
df.columns.tolist()

['RowNumber',
 'CustomerId',
 'Surname',
 'CreditScore',
 'Geography',
 'Gender',
 'Age',
 'Tenure',
 'Balance',
 'NumOfProducts',
 'HasCrCard',
 'IsActiveMember',
 'EstimatedSalary',
 'Exited',
 'Complain',
 'Satisfaction Score',
 'Card Type',
 'Point Earned']

In [4]:
# AgeGroup

In [5]:
def create_age_group(age):
    if age < 30:
        return "Young"
    elif age < 45:
        return "Adult"
    elif age < 60:
        return "Middle-aged"
    else:
        return "Senior"

df["AgeGroup"] = df["Age"].apply(create_age_group)

In [7]:
df[["Age", "AgeGroup"]].head(10)

   Age     AgeGroup
0   42        Adult
1   41        Adult
2   42        Adult
3   39        Adult
4   43        Adult
5   44        Adult
6   50  Middle-aged
7   29        Young
8   44        Adult
9   27        Young

In [8]:
# Engaged

In [9]:
df["Engaged"] = df["IsActiveMember"]

In [10]:
df[["IsActiveMember", "Engaged"]].head(10)

   IsActiveMember  Engaged
0               1        1
1               1        1
2               0        0
3               0        0
4               1        1
5               0        0
6               1        1
7               0        0
8               1        1
9               1        1

In [14]:
# Tenure_Age_Ratio

In [15]:
df["Tenure_Age_Ratio"] = (df["Tenure"])

In [16]:
df[["Tenure", "Tenure_Age_Ratio"]].head(10)

   Tenure  Tenure_Age_Ratio
0       2                 2
1       1                 1
2       8                 8
3       1                 1
4       2                 2
5       8                 8
6       7                 7
7       4                 4
8       4                 4
9       2                 2

In [17]:
# Balance_Salary_Ratio

In [18]:
df["Balance_Salary_Ratio"] = (df["Balance"])

In [21]:
df[["Balance", "Balance_Salary_Ratio"]].head(10)

     Balance  Balance_Salary_Ratio
0       0.00                  0.00
1   83807.86              83807.86
2  159660.80             159660.80
3       0.00                  0.00
4  125510.82             125510.82
5  113755.78             113755.78
6       0.00                  0.00
7  115046.74             115046.74
8  142051.07             142051.07
9  134603.88             134603.88

In [22]:
# ZeroBalance

In [23]:
df["ZeroBalance"] = (df["Balance"] == 0).astype(int)

In [24]:
df[["Balance", "ZeroBalance"]].head(10)

     Balance  ZeroBalance
0       0.00            1
1   83807.86            0
2  159660.80            0
3       0.00            1
4  125510.82            0
5  113755.78            0
6       0.00            1
7  115046.74            0
8  142051.07            0
9  134603.88            0